services:
  soaauth:
    image: soaauth
    ports:
      - "80:80"
    environment:
      BIND_ADDR: "0.0.0.0:80"
      DISCORD_CLIENT_ID: <discord oauth2 client secret>
      DISCORD_CLIENT_SECRET: <discord oauth2 client id>
      DATA_DIR: "/tmp"
      OAUTH2_URI: <URI used in oauth2 redirect>
      FORWARD_URI: <URI to redirect to after successful authentication>
